export const OPCIONES_CONTENIDO_MOCHILA: string[] = [
"Llave Mixta de 10 mm",
"Llave Mixta de 13 mm",
'Llave Española 1/2" - 9/16"',
'Llave Mixta de 7/16"',
"Perico de 10 pulgadas",
"Desarmador Plano",
"Desarmador de Cruz",
"Pinzas de Mecánico",
"Pinzas de Corte",
"Pinzas de Corte (Craftsman)",
"Eslinga de Sujeción",
"Lazo de Sujeción",
"Barbiquejo",
"Faja de Seguridad",
"Chaleco reflectante",
"Gafas de Seguridad",
"Guantes de Nylon",
"Guantes de Carneza",
"Cubrebocas de Tela",
"Franela",
"Gel antibacteriano",
];
