// Banco de preguntas: Capacitación "Procedimientos ATC"
// Generado a partir del documento "PROCEDIMIENTO RECURSOS HUMANOS TRANSPORTES LOGISTICAR"
// (Departamento de Atención a Clientes): introducción, objetivos, alcance, responsabilidades,
// clientes/almacenes, validación de rutas, análisis de evidencias, rol de actividades y
// empate de evidencias (Khuene + Nagel y Geodis).

export type OpcionLetra = "A" | "B" | "C" | "D";

export interface PreguntaProcedimientosAtc {
  numero: number;
  seccion: string;
  pregunta: string;
  opciones: Record<OpcionLetra, string>;
  correcta: OpcionLetra;
}

export const PREGUNTAS_PROCEDIMIENTOS_ATC: PreguntaProcedimientosAtc[] = [
  { numero: 1, seccion: "Introducción y objetivos", pregunta: "¿Cuál es la finalidad principal del Departamento de Atención a Clientes de Transportes Logisticar?", opciones: { A: "Administrar el pago de nómina de los operadores.", B: "Asegurar la satisfacción de los clientes mediante una atención eficiente, oportuna y profesional antes, durante y después del servicio.", C: "Supervisar exclusivamente el mantenimiento mecánico de las unidades.", D: "Fijar unilateralmente las tarifas de flete de cada cliente." }, correcta: "B" },
  { numero: 2, seccion: "Introducción y objetivos", pregunta: "Según el objetivo general del procedimiento, ¿qué se busca garantizar además de la satisfacción del cliente?", opciones: { A: "La reducción de costos operativos por encima de cualquier otro factor.", B: "La contratación acelerada de nuevo personal administrativo.", C: "La confianza, la lealtad y una comunicación efectiva orientada al cumplimiento exitoso de las entregas.", D: "La eliminación de intermediarios logísticos en la cadena de suministro." }, correcta: "C" },
  { numero: 3, seccion: "Alcance y responsabilidades", pregunta: "¿A quién aplica este procedimiento según el apartado de Alcance?", opciones: { A: "Únicamente a los operadores de las unidades.", B: "A todo el personal del Departamento de Atención a Clientes y a las áreas involucradas en la gestión de solicitudes, reclamos y seguimiento post-servicio.", C: "Exclusivamente al personal de seguridad de los clientes.", D: "Solo a los gerentes de cuenta asignados a cada cliente." }, correcta: "B" },
  { numero: 4, seccion: "Alcance y responsabilidades", pregunta: "¿Cuál de las siguientes es una responsabilidad explícita del Departamento de Atención a Clientes señalada en el procedimiento?", opciones: { A: "Elaboración de cartas porte.", B: "Reparación mecánica de las unidades.", C: "Contratación directa de operadores.", D: "Definición de rutas de tránsito federal." }, correcta: "A" },
  { numero: 5, seccion: "Clientes y almacenes", pregunta: "¿Cuáles son los dos almacenes bajo la cuenta Khuene + Nagel descritos en el procedimiento?", opciones: { A: "Tres Ríos y Prologis Park Grande.", B: "Geodis Tultepec y Almacén Buffer.", C: "Master Distribution Center (MDC EDOMEX) y Almacén Buffer.", D: "Almacén Buffer y Geodis Tultepec." }, correcta: "C" },
  { numero: 6, seccion: "Clientes y almacenes", pregunta: "¿Qué cuentas se administran en el Master Distribution Center (MDC EDOMEX)?", opciones: { A: "Under Armour, Loccitane y PMM.", B: "Dell, S2GO (Solutions Two Go) y Lexmark.", C: "Schneider y PUMA.", D: "LEGO y Nestlé." }, correcta: "B" },
  { numero: 7, seccion: "Clientes y almacenes", pregunta: "En el Almacén Buffer de Khuene + Nagel, ¿qué cuenta se administra principalmente?", opciones: { A: "Schneider.", B: "Dell.", C: "PUMA.", D: "LEGO." }, correcta: "A" },
  { numero: 8, seccion: "Clientes y almacenes", pregunta: "Dentro de los almacenes de Geodis, ¿qué cuentas se administran en Tres Ríos, y cuáles en Prologis Park Grande y Geodis Tultepec respectivamente?", opciones: { A: "Tres Ríos: Under Armour, Loccitane, PMM, Mindray, Steve Madden y Nestlé; Prologis Park Grande: LEGO; Geodis Tultepec: PUMA.", B: "Tres Ríos: LEGO; Prologis Park Grande: PUMA; Geodis Tultepec: Under Armour.", C: "Las tres ubicaciones administran exclusivamente Dell y S2GO.", D: "Tres Ríos: PUMA; Prologis Park Grande: Under Armour; Geodis Tultepec: LEGO." }, correcta: "A" },
  { numero: 9, seccion: "Validación de rutas", pregunta: "¿Cuál es el objetivo principal de la actividad de Validación de Rutas?", opciones: { A: "Verificar que los viajes programados diariamente estén correctamente cargados y que las unidades cumplan con los horarios establecidos.", B: "Calcular el rendimiento de combustible de cada unidad.", C: "Determinar la antigüedad y el valor de reventa de cada unidad.", D: "Registrar las vacaciones y permisos de los operadores." }, correcta: "A" },
  { numero: 10, seccion: "Validación de rutas", pregunta: "Según el procedimiento, ¿qué equipo de seguridad debe portar el operador y qué eventualidades externas se supervisan durante la validación de rutas?", opciones: { A: "Solo casco; se supervisan exclusivamente fallas mecánicas.", B: "Botas, casco, pantalón sin roturas y playera blanca; se supervisan accidentes, manifestaciones, cierres viales, detenciones o fallas mecánicas.", C: "Uniforme completo de gala; se supervisa únicamente el clima.", D: "Chaleco reflectante; se supervisan los horarios de comida del operador." }, correcta: "B" },
  { numero: 11, seccion: "Análisis y revisión de evidencias", pregunta: "¿Qué debe evidenciar la firma y/o sello presente en las remisiones o facturas?", opciones: { A: "Que el cliente aceptó una cotización de servicio.", B: "Que la mercancía fue entregada por los operadores y recibida correctamente por el cliente.", C: "Que el operador recibió su pago correspondiente.", D: "Que la unidad aprobó su verificación vehicular." }, correcta: "B" },
  { numero: 12, seccion: "Análisis y revisión de evidencias", pregunta: "¿A través de qué medio deben los operadores enviar las evidencias de sus servicios, y en qué sistema deben subirlas?", opciones: { A: "Correo electrónico personal; sistema SAP.", B: "Grupos de WhatsApp designados para cada cliente; sistema Control Track.", C: "Mensajería SMS; plataforma Alpha.", D: "Entrega física únicamente, sin subirla a ningún sistema." }, correcta: "B" },
  { numero: 13, seccion: "Análisis y revisión de evidencias", pregunta: "¿Con qué frecuencia se realiza la verificación de las evidencias de entrega según el procedimiento?", opciones: { A: "Solo al finalizar la semana laboral.", B: "De manera continua durante la jornada laboral, conforme las unidades completan sus entregas.", C: "Únicamente cuando el cliente presenta una queja formal.", D: "Cada quince días, de forma programada." }, correcta: "B" },
  { numero: 14, seccion: "Rol de actividades", pregunta: "Al inicio de la jornada, al revisar la base 'Control de Viajes', ¿qué información específica se confirma?", opciones: { A: "Únicamente el nombre del cliente final.", B: "La cuenta asignada, número de embarque, nombre del operador, número de unidad y el registro de su puntualidad en la cita de carga.", C: "El estado del clima proyectado en la ruta.", D: "El kilometraje total acumulado de la unidad." }, correcta: "B" },
  { numero: 15, seccion: "Rol de actividades", pregunta: "Al contactar a los operadores para verificar el estado de cada servicio (cargada, en espera de documentación o en ruta), ¿qué otros datos se validan?", opciones: { A: "El precio del combustible consumido en el trayecto.", B: "La cantidad de cajas o pallets transportados, el número de entregas (tiros) y la existencia de citas programadas.", C: "El historial de infracciones del operador.", D: "Únicamente el modelo del vehículo." }, correcta: "B" },
  { numero: 16, seccion: "Rol de actividades", pregunta: "En la elaboración de las facturas de los servicios programados del día, ¿cuál es el criterio de prioridad establecido en el procedimiento?", opciones: { A: "Se facturan primero los servicios locales por ser más rápidos de procesar.", B: "Se priorizan los servicios foráneos para prevenir posibles sanciones de tránsito durante los retenes, y después se generan las facturas locales.", C: "Se factura estrictamente en el orden en que llegan las evidencias, sin distinción.", D: "Se priorizan los servicios de mayor monto económico." }, correcta: "B" },
  { numero: 17, seccion: "Rol de actividades", pregunta: "Cuando un operador reporta evidencias de entrega que no cuentan con el sello del cliente, ¿qué acción indica el procedimiento?", opciones: { A: "Se rechaza automáticamente la evidencia y se cancela la factura.", B: "Se debe indicar la leyenda 'sin sello'.", C: "Se solicita al operador que regrese al cliente exclusivamente por el sello.", D: "Se sustituye el sello faltante con la firma del gerente de Atención a Clientes." }, correcta: "B" },
  { numero: 18, seccion: "Rol de actividades", pregunta: "Para clientes como Liverpool, Sears, Palacio de Hierro o Walmart, ¿dónde se localiza el número de referencia utilizado para relacionar la documentación con el control de ruta?", opciones: { A: "En la esquina superior derecha del documento.", B: "En la parte central del documento, identificado como número de orden o folio.", C: "Al reverso de la remisión, junto al código de barras.", D: "En el sello de recepción del almacén del cliente." }, correcta: "B" },
  { numero: 19, seccion: "Rol de actividades", pregunta: "Cuando se detectan errores o inconsistencias en la documentación, ¿qué doble gestión se realiza de manera simultánea según el procedimiento?", opciones: { A: "Se notifica a Recursos Humanos y se suspende temporalmente al operador.", B: "Se establece comunicación con el cliente (correo electrónico o vía telefónica) y, de manera simultánea, se consulta al operador responsable para recabar información adicional y recuperar las evidencias faltantes.", C: "Se cancela la factura emitida y se genera una nueva orden de servicio.", D: "Se reporta el incidente a la aseguradora y se abre un expediente legal." }, correcta: "B" },
  { numero: 20, seccion: "Rol de actividades", pregunta: "¿Por qué es importante sacar una copia del control de ruta o ESMESO antes de que el cliente libere el servicio?", opciones: { A: "Porque es un requisito fiscal obligatorio ante el SAT.", B: "Porque cuando el cliente libera el servicio, devuelve esa copia con el sello de liberación y revisión, indicando si hubo devoluciones o algún comentario adicional.", C: "Porque el operador la necesita para cobrar su viático de campo.", D: "Porque sustituye a la factura original en caso de pérdida." }, correcta: "B" },
  { numero: 21, seccion: "Rol de actividades", pregunta: "Cuando se entregan dispositivos GPS de las cuentas Dell o Under Armour, y una vez que los controles de ruta/ESMESOS regresan sellados por el cliente, ¿qué acciones señala el procedimiento?", opciones: { A: "Se registra el número de serie del equipo y la fecha programada de entrega en la base 'GPS 2025'; los documentos sellados se escanean y guardan en la carpeta 'Evidencias liberadas', renombrados con la fecha de entrega, y se entregan a la Sra. Leticia Neri para el cobro correspondiente.", B: "El dispositivo GPS se entrega sin registro alguno y los documentos se destruyen tras su revisión.", C: "Se envían los documentos sellados directamente al cliente por correo certificado, sin conservar copia.", D: "El registro se realiza únicamente en la base 'Book', sin relación con los ESMESOS." }, correcta: "A" },
  { numero: 22, seccion: "Rol de actividades", pregunta: "Respecto a la base de servicios PUMA (Geodis), ¿cuál es su periodicidad, el periodo de cierre y el plazo límite de envío?", opciones: { A: "Es diaria, cierra de lunes a viernes y se envía antes del mediodía.", B: "Es semanal, con un periodo de cierre de lunes a lunes, y debe enviarse todos los lunes antes de las 10 de la mañana.", C: "Es mensual, cierra el último día del mes y se envía en la primera semana del mes siguiente.", D: "Es quincenal y no tiene un horario límite de envío establecido." }, correcta: "B" },
  { numero: 23, seccion: "Rol de actividades", pregunta: "¿Qué campos es obligatorio completar al actualizar la base 'Book' (proporcionada por Rubén Castillo) para la cuenta DELL?", opciones: { A: "Únicamente el número de factura.", B: "El nombre de la persona que recibe la mercancía y la fecha de recepción.", C: "El costo total del servicio y el margen de utilidad.", D: "El número de placas de la unidad y el nombre del operador." }, correcta: "B" },
  { numero: 24, seccion: "Empate de evidencias — Khuene + Nagel", pregunta: "¿Cómo se distinguen entre sí los viajes gestionados por KN respecto a los administrados por Geodis en cuanto a su control de ruta, y qué información esencial contiene el control de ruta de KN?", opciones: { A: "Los viajes de KN se distinguen por un control de ruta de siete números consecutivos, mientras que los de Geodis se identifican con los prefijos ESMESO o MXC; el control de ruta de KN incluye número de embarque, operador, tipo de unidad, fecha y hora de carga y salida, cliente, peso total, número de remisiones y cantidad total de cajas.", B: "Ambos utilizan exactamente el mismo formato de folio numérico, sin ninguna diferencia entre sí.", C: "Los viajes de KN se identifican con el prefijo ESMESO y los de Geodis con siete números consecutivos.", D: "El control de ruta de KN únicamente contiene el nombre del cliente y la fecha de entrega." }, correcta: "A" },
  { numero: 25, seccion: "Empate de evidencias — Khuene + Nagel", pregunta: "Para el cliente Schneider, ¿con qué documento se empatan las evidencias y cómo se identifica el número de orden correspondiente?", opciones: { A: "Con el control de ruta únicamente, sin necesidad de factura.", B: "Con las facturas, identificando el número de orden señalado en la factura como 'Delivery'.", C: "Con la hoja de no penalización emitida por el cliente.", D: "Con el acuse de validación de recolección sellado por el propio cliente." }, correcta: "B" },
  { numero: 26, seccion: "Empate de evidencias — Khuene + Nagel", pregunta: "¿Qué distingue el manejo de evidencias del cliente PROVA respecto a otros clientes de Khuene + Nagel?", opciones: { A: "Requiere factura, orden de compra y control de ruta firmados simultáneamente.", B: "Este cliente sella únicamente el control de ruta, registrando la fecha de recepción de la mercancía, el nombre y el número de cajas o pallets recibidos.", C: "No requiere ningún tipo de sello, firma ni documento adicional.", D: "Se empata exclusivamente con la hoja verde de encuesta de servicio." }, correcta: "B" },
  { numero: 27, seccion: "Empate de evidencias — Khuene + Nagel", pregunta: "Para el cliente FLAVORS, además de las remisiones firmadas, ¿qué requisito adicional se exige sobre la factura o la orden de compra?", opciones: { A: "Debe entregarse acompañada de una copia notariada.", B: "Debe venir firmada como comprobante de entrega.", C: "Debe incluir el sello de la casa de seguridad Overhaul.", D: "No se requiere ningún documento adicional a las remisiones." }, correcta: "B" },
  { numero: 28, seccion: "Empate de evidencias — Khuene + Nagel", pregunta: "¿Con qué documentos se empata el servicio para clientes como Liverpool, Palacio de Hierro, Walmart y Soriana, y qué documento adicional exige específicamente SEARS?", opciones: { A: "Ambos grupos se empatan únicamente con la factura; SEARS no requiere documentos adicionales.", B: "Se empatan con control de ruta, factura y folio; SEARS además requiere una hoja de no penalización.", C: "Se empatan con ESMESO y encuesta de satisfacción; SEARS requiere el acuse de GPS.", D: "Se empatan únicamente con la orden de compra; SEARS requiere el control de ruta sellado por el cliente." }, correcta: "B" },
  { numero: 29, seccion: "Empate de evidencias — Khuene + Nagel", pregunta: "Para las recolecciones de INGRAM (cuenta Dell), ¿con qué documentos se realiza el empate de evidencias?", opciones: { A: "Únicamente con el control de ruta.", B: "Con control de ruta, el acuse de validación de recolección DELL (sellado por DELL) y la tabla de órdenes de compra.", C: "Solo con la factura y el CFDI impreso.", D: "Con la hoja verde de encuesta de servicio." }, correcta: "B" },
  { numero: 30, seccion: "Empate de evidencias — Geodis", pregunta: "¿Qué información clave integra el ESMESO utilizado en los servicios de Geodis?", opciones: { A: "Únicamente el nombre del cliente y la fecha de entrega.", B: "Número de embarque, nombre del operador, tipo de unidad, fecha y hora de carga y salida, cliente, número de remisiones y total de cajas transportadas.", C: "El costo total del flete y las condiciones de pago pactadas.", D: "La ruta GPS exacta seguida por la unidad durante el trayecto." }, correcta: "B" },
  { numero: 31, seccion: "Empate de evidencias — Geodis", pregunta: "Para el cliente UNDER ARMOUR, ¿qué debe contener el ESMESO como parte de las evidencias, y con qué documento se complementa?", opciones: { A: "Solo la firma del operador; se complementa con la factura del cliente.", B: "El sello del almacén de Under Armour donde se efectuó la carga, el nombre de quien realizó la entrega y el número de cajas o pallets cargados; se complementa con el control de carga, donde se especifican las órdenes y la cantidad de piezas entregadas.", C: "Únicamente el número de placas de la unidad; no requiere documento adicional.", D: "La firma del gerente de seguridad de Under Armour; se complementa con el acuse de GPS." }, correcta: "B" },
  { numero: 32, seccion: "Empate de evidencias — Geodis", pregunta: "Las evidencias del cliente LOCCITANE se empatan con el ESMESO y, ¿qué tres documentos adicionales se requieren específicamente?", opciones: { A: "Factura, orden de compra y hoja de no penalización.", B: "Su carta de embarque, lista de empaque y CFDI impreso.", C: "Encuesta de satisfacción, control de carga y acuse de GPS.", D: "Confirmación de recolección, factura y control de ruta." }, correcta: "B" },
  { numero: 33, seccion: "Empate de evidencias — Geodis", pregunta: "Para las recolecciones del cliente PMM, ¿con qué documentos se realiza el empate de evidencias?", opciones: { A: "ESMESO, confirmación de recolección y CFDI impreso.", B: "Control de ruta, factura y hoja verde de encuesta.", C: "ESMESO y acuse de entrega de mercancía únicamente.", D: "Carta de embarque y lista de empaque." }, correcta: "A" },
  { numero: 34, seccion: "Empate de evidencias — Geodis", pregunta: "¿Qué documentos se requieren para empatar las evidencias de MINDRAY y de STEVE MADDEN, respectivamente?", opciones: { A: "MINDRAY: ESMESO y acuse de entrega de mercancía; STEVE MADDEN: ESMESO y CFDI impreso.", B: "MINDRAY: hoja verde y factura; STEVE MADDEN: control de carga y CFDI.", C: "Ambos clientes requieren únicamente la carta de embarque.", D: "MINDRAY: confirmación de recolección; STEVE MADDEN: control de ruta sellado." }, correcta: "A" },
  { numero: 35, seccion: "Empate de evidencias — Geodis", pregunta: "Respecto a la cuenta LEGO, ¿en qué se dividen las evidencias y qué documentos se integran específicamente para las entregas en los centros comerciales Walmart y Sam's Club?", opciones: { A: "Se dividen por tipo de unidad utilizada; para Walmart y Sam's solo se requiere el ESMESO.", B: "Se dividen entre las entregas realizadas en centros comerciales (Walmart y Sam's) y las entregas efectuadas en jugueterías; para Walmart y Sam's se integra el ESMESO, la hoja de confirmación de cita, el pase vehicular, la relación de facturas y todas las facturas correspondientes a la mercancía entregada.", C: "Se dividen por región geográfica de entrega; ambas modalidades requieren solo el CFDI impreso.", D: "Se dividen entre entregas urgentes y programadas; ninguna requiere documentación adicional." }, correcta: "B" },
];

export const PREGUNTAS_POR_PAGINA_ATC = 5;
export const TOTAL_PREGUNTAS_ATC = PREGUNTAS_PROCEDIMIENTOS_ATC.length;
export const TOTAL_PAGINAS_ATC = Math.ceil(TOTAL_PREGUNTAS_ATC / PREGUNTAS_POR_PAGINA_ATC);
