export const CAMPOS_UNIDAD: string[] = [
"ECO",
"Unidad",
"VIN",
"No de motor",
"Tipo de aceite que usa",
"Medida STD de llantas",
"Capacidad de litros de aceite",
"Capacidad del tanque de combustible (L)",
"Placa",
"Año",
"Marca",
"Modelo/Tipo",
"Rendimiento (km/l)",
"Color",
"IAVE",
"Ancho (m)",
"Alto (m)",
"Largo (m)",
"Vol. (m3)",
"Propietario",
"Ref. Capacidad",
"Clave",
"Capacidad (Kg)",
"Uso",
"Cia. Poliza",
"No. Poliza",
"Vigencia",
"Vigencia Anterior",
"Estatus poliza",
];
